[project]
name = "handyapi"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastapi[standard]>=0.115.12",
]

[dependency-groups]
dev = [
    "fastapi[standard]>=0.115.12",
]

[tool.autopep8]
max-line-length = 80
